export const NvrManufacturer = {
    SearchList: [
        'DIGIEVER',
        'Digifort',
        'Diviotec (Linux)',
        'Hikvision',
        'iSap',
        'SAMSUNG',
        'VioStor'],
    EditorList: [
        '3TSmart',
        'ACTi',
        'ACTi Enterprise',
        'Aimetis',
        'Certis',
        'Customization',
        'Dahua',
        'DIGIEVER',
        'Digifort',
        'Diviotec (Linux)',
        'Diviotec (Windows)',
        'Hikvision',
        'iSap',
        'iSap Failover Server',
        'iSapP2P',
        'Milestone',
        'Milestone Corporate 2016 R2',
        'NetworkOptix',
        'ONVIF',
        'Salient',
        'SAMSUNG',
        'ShanyLink',
        'Siemens',
        // 'SmartMedia',
        'VioStor',
        'VIVOTEK']
};
export default NvrManufacturer;
